language: python

sudo: required
dist: trusty

matrix:
    include:
        - env: ELASTIC2X
          python: "3.6"
          addons:
              apt:
                  sources:
                      - elasticsearch-2.x
                  packages:
                      - elasticsearch

        - env: ELASTIC2X
          python: "3.5"
          addons:
              apt:
                  sources:
                      - elasticsearch-2.x
                  packages:
                      - elasticsearch

        - env: ELASTIC2X
          python: "3.4"
          addons:
              apt:
                  sources:
                      - elasticsearch-2.x
                  packages:
                      - elasticsearch

        - env: ELASTIC2X
          python: "2.7"
          addons:
              apt:
                  sources:
                      - elasticsearch-2.x
                  packages:
                      - elasticsearch

        - env: ELASTIC17
          python: "3.5"
          addons:
              apt:
                  sources:
                      - elasticsearch-1.7
                  packages:
                      - elasticsearch

install:
    - pip install -r requirements.txt
    - pip install .

script:
    - nosetests
    - flake8

services:
    - elasticsearch
