language: python

cache:
  - pip

services:
    - docker

env:
    matrix:
        - ELASTIC_VERSION=7.3.0
        - ELASTIC_VERSION=7.2.1
        - ELASTIC_VERSION=7.1.1
        - ELASTIC_VERSION=7.0.1
        - ELASTIC_VERSION=6.8.2
        - ELASTIC_VERSION=5.6.16

install:
    - docker pull "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}"
    - docker run -d -p 9200:9200 -e "discovery.type=single-node" "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}"
    - pip install -r requirements.txt
    - pip install .

script:
    - nosetests
    - black --check eve_elastic test *.py
