language: python

services:
    - docker

install:
    - docker-compose up -d
    - pip install -r requirements.txt
    - pip install .

script:
    - black --check eve_elastic test *.py
    - nosetests
